### ISSUE TITLE
 Redux Store가 undefined

### ISSUE THREAD

**Issue by dusunax** [dusunax/react-assignment-chapter4-hanghae#2]
1. Redux Store가 undefined 뜸
```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at TodoList (TodoList.jsx:11:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

최근 업데이트: redux-thunk  / firebase 연결

**Comment by dusunax** [comment]
**해결 방법**: 실행하고 있는 map 주석처리하고  
console에 state부터 다시 찍음  

`const data = useSelector((state) => state.note.list)`에서  
 `const data = useSelector((state) => state.note.state.list)`로 변경  

createStore에 미들웨어가 추가되면서 store의 구조가 바뀜 => 에러 발생
